### ISSUE TITLE
Application Share Audio 

### ISSUE THREAD

**Issue by lokemoh** [Pavo-IM/amd_hackintosh_discord_fix#2]
Hey when we share application, audio is not shared. I have tried it several times with multiple applications. Im using a A520 Asus prime and a Ryzen 5 3600, using AppleALC kext for audio. Let me know if there is any solution to this or if it works fine for everyone in general.

**Comment by fabioavf** [comment]
That's a limitation on Discord's version of MacOS. Nothing related to Hackintosh.

**Comment by Pavo-IM** [comment]
That is how it works normally for macOS apps that have a screensharing feature. You need to use a secondary application like Loopback or similar to capture the audio and pipe it through as a virtual audio device.
